name: Deploy Todo Backend

on:
    workflow_dispatch:
    push:
        branches:
            - main
env:
  APP_NAME: todo-backend
  IMAGE_TAG: ${{github.sha}}
  CONTAINER_NAME: todo-backend-app

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    # source coude checkout
      - name: Checkout source code
        uses: actions/checkout@v6

    # setting up java
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

    # build sprin gboot project
      - name: Build Application
        run: |
            chmod +x mvnw
            ./mvnw clean package -DskipTests

    # Login to dockerhub
      - name: Login to docker hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # image build
      - name: Build docker image
        run: |
          docker build \
          -t ${{ vars.DOCKERHUB_USERNAME}}/${{env.APP_NAME}}:${{env.IMAGE_TAG}} \
          .
          echo "image build success"
          docker images

    # image push
      - name: Push the docker image
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME}}/${{env.APP_NAME}}:${{env.IMAGE_TAG}}
          echo "image pushed success"

    # Deploy on ec2:

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USERNAME }}
          key: ${{secrets.EC2_PASSWORD}}
          script: |
            docker pull ${{ vars.DOCKERHUB_USERNAME}}/${{env.APP_NAME}}:${{env.IMAGE_TAG}}
            docker stop ${{env.CONTAINER_NAME}} || true
            docker rm ${{env.CONTAINER_NAME}} || true
            docker run -d \
              --name ${{env.CONTAINER_NAME}} \
              -p 8080:8080 \
              ${{ vars.DOCKERHUB_USERNAME}}/${{env.APP_NAME}}:${{env.IMAGE_TAG}}
            docker image prune -f
            echo "deployment successful !!"



